// NOTE: All state data below (prelicensing hours, CE hours, exam questions/scores/times,
// DOI URLs, exam provider assignments) is based on best-effort research and MUST be
// manually verified against each state's current DOI and exam provider requirements
// before publishing. Regulations change frequently.

export interface StateExamInfo {
  questions: number;
  passingScore: number;
  timeLimit: string;
}

export interface CoursePricing {
  hours: number;
  price: string;
}

export interface CEPricing extends CoursePricing {
  renewalYears: number;
}

export interface StateData {
  name: string;
  abbreviation: string;
  slug: string;
  doiName: string;
  doiUrl: string;
  examProvider: string;
  examProviderUrl: string;
  examBookingUrl: string;
  noCombinedExam: boolean;
  applicationBeforeExam: boolean;
  prelicensing: {
    life: CoursePricing;
    health: CoursePricing;
    lifeAndHealth: CoursePricing;
  };
  ce: {
    life: CEPricing;
    health: CEPricing;
    lifeAndHealth: CEPricing;
  };
  examInfo: StateExamInfo;
}

// States confirmed to have NO combined Life & Health exam — must book separately
export const NO_COMBINED_EXAM_STATES = [
  "montana", "tennessee", "north-dakota", "alaska", "colorado",
  "hawaii", "idaho", "iowa", "new-jersey", "rhode-island",
  "west-virginia", "wisconsin"
];

// States where you must apply for your license BEFORE scheduling the exam
export const APPLICATION_BEFORE_EXAM_STATES = [
  "arkansas", "north-carolina", "kentucky", "kansas"
];

export const STATES: Record<string, StateData> = {
  alabama: {
    name: "Alabama",
    abbreviation: "AL",
    slug: "alabama",
    doiName: "Alabama Department of Insurance",
    doiUrl: "https://www.aldoi.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/alabama/insurance",
    examBookingUrl: "https://training.ua.edu/insurance-testing/#registration",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  alaska: {
    name: "Alaska",
    abbreviation: "AK",
    slug: "alaska",
    doiName: "Alaska Division of Insurance",
    doiUrl: "https://www.commerce.alaska.gov/web/ins",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/alaska/insurance",
    examBookingUrl: "https://home.pearsonvue.com/ak/insurance",
    noCombinedExam: true,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  arizona: {
    name: "Arizona",
    abbreviation: "AZ",
    slug: "arizona",
    doiName: "Arizona Department of Insurance and Financial Institutions",
    doiUrl: "https://difi.az.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/arizona/insurance",
    examBookingUrl: "https://home.pearsonvue.com/az/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  arkansas: {
    name: "Arkansas",
    abbreviation: "AR",
    slug: "arkansas",
    doiName: "Arkansas Insurance Department",
    doiUrl: "https://www.insurance.arkansas.gov",
    examProvider: "PSI",
    examProviderUrl: "https://test-takers.psiexams.com/arins",
    examBookingUrl: "https://test-takers.psiexams.com/arins",
    noCombinedExam: false,
    applicationBeforeExam: true,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  california: {
    name: "California",
    abbreviation: "CA",
    slug: "california",
    doiName: "California Department of Insurance",
    doiUrl: "https://www.insurance.ca.gov",
    examProvider: "PSI",
    examProviderUrl: "https://test-takers.psiexams.com/cadi",
    examBookingUrl: "https://test-takers.psiexams.com/cadi",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 60, timeLimit: "3 hours" },
  },
  colorado: {
    name: "Colorado",
    abbreviation: "CO",
    slug: "colorado",
    doiName: "Colorado Division of Insurance",
    doiUrl: "https://doi.colorado.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/colorado/insurance",
    examBookingUrl: "https://home.pearsonvue.com/co/insurance",
    noCombinedExam: true,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  connecticut: {
    name: "Connecticut",
    abbreviation: "CT",
    slug: "connecticut",
    doiName: "Connecticut Insurance Department",
    doiUrl: "https://portal.ct.gov/CID",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/connecticut/insurance",
    examBookingUrl: "https://home.pearsonvue.com/ct/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  delaware: {
    name: "Delaware",
    abbreviation: "DE",
    slug: "delaware",
    doiName: "Delaware Department of Insurance",
    doiUrl: "https://insurance.delaware.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/delaware/insurance",
    examBookingUrl: "https://home.pearsonvue.com/de/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  florida: {
    name: "Florida",
    abbreviation: "FL",
    slug: "florida",
    doiName: "Florida Department of Financial Services",
    doiUrl: "https://www.myfloridacfo.com",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/florida/insurance",
    examBookingUrl: "https://home.pearsonvue.com/fl/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 40, price: "$199" },
      health: { hours: 40, price: "$199" },
      lifeAndHealth: { hours: 60, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 165, passingScore: 70, timeLimit: "2.5 hours" },
  },
  georgia: {
    name: "Georgia",
    abbreviation: "GA",
    slug: "georgia",
    doiName: "Georgia Office of Insurance and Safety Fire Commissioner",
    doiUrl: "https://oci.georgia.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/ga/insurance",
    examBookingUrl: "https://home.pearsonvue.com/ga/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  hawaii: {
    name: "Hawaii",
    abbreviation: "HI",
    slug: "hawaii",
    doiName: "Hawaii Insurance Division",
    doiUrl: "https://cca.hawaii.gov/ins",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/hawaii/insurance",
    examBookingUrl: "https://home.pearsonvue.com/hi/insurance",
    noCombinedExam: true,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  idaho: {
    name: "Idaho",
    abbreviation: "ID",
    slug: "idaho",
    doiName: "Idaho Department of Insurance",
    doiUrl: "https://doi.idaho.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/idaho/insurance",
    examBookingUrl: "https://home.pearsonvue.com/id/insurance",
    noCombinedExam: true,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  illinois: {
    name: "Illinois",
    abbreviation: "IL",
    slug: "illinois",
    doiName: "Illinois Department of Insurance",
    doiUrl: "https://insurance.illinois.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/illinois/insurance",
    examBookingUrl: "https://home.pearsonvue.com/il/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 30, price: "$59", renewalYears: 2 },
      health: { hours: 30, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 30, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  indiana: {
    name: "Indiana",
    abbreviation: "IN",
    slug: "indiana",
    doiName: "Indiana Department of Insurance",
    doiUrl: "https://www.in.gov/idoi",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/indiana/insurance",
    examBookingUrl: "https://home.pearsonvue.com/in/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  iowa: {
    name: "Iowa",
    abbreviation: "IA",
    slug: "iowa",
    doiName: "Iowa Insurance Division",
    doiUrl: "https://iid.iowa.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/iowa/insurance",
    examBookingUrl: "https://home.pearsonvue.com/ia/insurance",
    noCombinedExam: true,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 36, price: "$59", renewalYears: 3 },
      health: { hours: 36, price: "$59", renewalYears: 3 },
      lifeAndHealth: { hours: 36, price: "$59", renewalYears: 3 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  kansas: {
    name: "Kansas",
    abbreviation: "KS",
    slug: "kansas",
    doiName: "Kansas Insurance Department",
    doiUrl: "https://insurance.ks.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/ks/insurance",
    examBookingUrl: "https://home.pearsonvue.com/ks/insurance",
    noCombinedExam: false,
    applicationBeforeExam: true,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 16, price: "$59", renewalYears: 2 },
      health: { hours: 16, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 16, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  kentucky: {
    name: "Kentucky",
    abbreviation: "KY",
    slug: "kentucky",
    doiName: "Kentucky Department of Insurance",
    doiUrl: "https://doi.ky.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/kentucky/insurance",
    examBookingUrl: "https://insurance.ky.gov/doieservices",
    noCombinedExam: false,
    applicationBeforeExam: true,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  louisiana: {
    name: "Louisiana",
    abbreviation: "LA",
    slug: "louisiana",
    doiName: "Louisiana Department of Insurance",
    doiUrl: "https://www.ldi.la.gov",
    examProvider: "PSI",
    examProviderUrl: "https://test-takers.psiexams.com/ladi",
    examBookingUrl: "https://test-takers.psiexams.com/ladi",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  maine: {
    name: "Maine",
    abbreviation: "ME",
    slug: "maine",
    doiName: "Maine Bureau of Insurance",
    doiUrl: "https://www.maine.gov/pfr/insurance",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/maine/insurance",
    examBookingUrl: "https://home.pearsonvue.com/me/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  maryland: {
    name: "Maryland",
    abbreviation: "MD",
    slug: "maryland",
    doiName: "Maryland Insurance Administration",
    doiUrl: "https://insurance.maryland.gov",
    examProvider: "PSI",
    examProviderUrl: "https://candidate.psiexams.com",
    examBookingUrl: "https://home.pearsonvue.com/md/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  massachusetts: {
    name: "Massachusetts",
    abbreviation: "MA",
    slug: "massachusetts",
    doiName: "Massachusetts Division of Insurance",
    doiUrl: "https://www.mass.gov/orgs/division-of-insurance",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/massachusetts/insurance",
    examBookingUrl: "https://home.pearsonvue.com/ma/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 40, price: "$199" },
      health: { hours: 40, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 18, price: "$59", renewalYears: 2 },
      health: { hours: 18, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 18, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  michigan: {
    name: "Michigan",
    abbreviation: "MI",
    slug: "michigan",
    doiName: "Michigan Department of Insurance and Financial Services",
    doiUrl: "https://www.michigan.gov/difs",
    examProvider: "PSI",
    examProviderUrl: "https://test-takers.psiexams.com/midifs",
    examBookingUrl: "https://test-takers.psiexams.com/midifs",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  minnesota: {
    name: "Minnesota",
    abbreviation: "MN",
    slug: "minnesota",
    doiName: "Minnesota Department of Commerce",
    doiUrl: "https://mn.gov/commerce",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/minnesota/insurance",
    examBookingUrl: "https://home.pearsonvue.com/mn/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  mississippi: {
    name: "Mississippi",
    abbreviation: "MS",
    slug: "mississippi",
    doiName: "Mississippi Insurance Department",
    doiUrl: "https://www.mid.ms.gov",
    examProvider: "PSI",
    examProviderUrl: "https://candidate.psiexams.com",
    examBookingUrl: "https://home.pearsonvue.com/ms/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  missouri: {
    name: "Missouri",
    abbreviation: "MO",
    slug: "missouri",
    doiName: "Missouri Department of Commerce and Insurance",
    doiUrl: "https://insurance.mo.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/missouri/insurance",
    examBookingUrl: "https://home.pearsonvue.com/mo/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 16, price: "$59", renewalYears: 2 },
      health: { hours: 16, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 16, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  montana: {
    name: "Montana",
    abbreviation: "MT",
    slug: "montana",
    doiName: "Montana Commissioner of Securities and Insurance",
    doiUrl: "https://csimt.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/mt/insurance",
    examBookingUrl: "https://home.pearsonvue.com/mt/insurance",
    noCombinedExam: true,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  nebraska: {
    name: "Nebraska",
    abbreviation: "NE",
    slug: "nebraska",
    doiName: "Nebraska Department of Insurance",
    doiUrl: "https://doi.nebraska.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/nebraska/insurance",
    examBookingUrl: "https://home.pearsonvue.com/ne/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 30, price: "$59", renewalYears: 2 },
      health: { hours: 30, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 30, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  nevada: {
    name: "Nevada",
    abbreviation: "NV",
    slug: "nevada",
    doiName: "Nevada Division of Insurance",
    doiUrl: "https://doi.nv.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/nevada/insurance",
    examBookingUrl: "https://home.pearsonvue.com/nv/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 30, price: "$59", renewalYears: 3 },
      health: { hours: 30, price: "$59", renewalYears: 3 },
      lifeAndHealth: { hours: 30, price: "$59", renewalYears: 3 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  "new-hampshire": {
    name: "New Hampshire",
    abbreviation: "NH",
    slug: "new-hampshire",
    doiName: "New Hampshire Insurance Department",
    doiUrl: "https://www.nh.gov/insurance",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/new-hampshire/insurance",
    examBookingUrl: "https://home.pearsonvue.com/nh/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  "new-jersey": {
    name: "New Jersey",
    abbreviation: "NJ",
    slug: "new-jersey",
    doiName: "New Jersey Department of Banking and Insurance",
    doiUrl: "https://www.state.nj.us/dobi",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/new-jersey/insurance",
    examBookingUrl: "https://home.pearsonvue.com/nj/insurance",
    noCombinedExam: true,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  "new-mexico": {
    name: "New Mexico",
    abbreviation: "NM",
    slug: "new-mexico",
    doiName: "New Mexico Office of Superintendent of Insurance",
    doiUrl: "https://www.osi.state.nm.us",
    examProvider: "PSI",
    examProviderUrl: "https://test-takers.psiexams.com/nmins",
    examBookingUrl: "https://test-takers.psiexams.com/nmins",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  "new-york": {
    name: "New York",
    abbreviation: "NY",
    slug: "new-york",
    doiName: "New York Department of Financial Services",
    doiUrl: "https://www.dfs.ny.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/new-york/insurance",
    examBookingUrl: "https://home.pearsonvue.com/ny/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 40, price: "$199" },
      health: { hours: 40, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 15, price: "$59", renewalYears: 2 },
      health: { hours: 15, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 15, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  "north-carolina": {
    name: "North Carolina",
    abbreviation: "NC",
    slug: "north-carolina",
    doiName: "North Carolina Department of Insurance",
    doiUrl: "https://www.ncdoi.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/north-carolina/insurance",
    examBookingUrl: "https://home.pearsonvue.com/nc/insurance",
    noCombinedExam: false,
    applicationBeforeExam: true,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  "north-dakota": {
    name: "North Dakota",
    abbreviation: "ND",
    slug: "north-dakota",
    doiName: "North Dakota Insurance Department",
    doiUrl: "https://www.insurance.nd.gov",
    examProvider: "PSI",
    examProviderUrl: "https://test-takers.psiexams.com/ndins",
    examBookingUrl: "https://test-takers.psiexams.com/ndins",
    noCombinedExam: true,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  ohio: {
    name: "Ohio",
    abbreviation: "OH",
    slug: "ohio",
    doiName: "Ohio Department of Insurance",
    doiUrl: "https://insurance.ohio.gov",
    examProvider: "PSI",
    examProviderUrl: "https://psiexams.com/ohins",
    examBookingUrl: "https://psiexams.com/ohins",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  oklahoma: {
    name: "Oklahoma",
    abbreviation: "OK",
    slug: "oklahoma",
    doiName: "Oklahoma Insurance Department",
    doiUrl: "https://www.oid.ok.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/oklahoma/insurance",
    examBookingUrl: "https://home.pearsonvue.com/ok/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  oregon: {
    name: "Oregon",
    abbreviation: "OR",
    slug: "oregon",
    doiName: "Oregon Insurance Division",
    doiUrl: "https://dfr.oregon.gov/insure",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/oregon/insurance",
    examBookingUrl: "https://home.pearsonvue.com/or/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  pennsylvania: {
    name: "Pennsylvania",
    abbreviation: "PA",
    slug: "pennsylvania",
    doiName: "Pennsylvania Insurance Department",
    doiUrl: "https://www.insurance.pa.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/pennsylvania/insurance",
    examBookingUrl: "https://home.pearsonvue.com/pa/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 24, price: "$199" },
      health: { hours: 24, price: "$199" },
      lifeAndHealth: { hours: 24, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  "rhode-island": {
    name: "Rhode Island",
    abbreviation: "RI",
    slug: "rhode-island",
    doiName: "Rhode Island Department of Business Regulation – Insurance Division",
    doiUrl: "https://dbr.ri.gov/insurance",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/rhode-island/insurance",
    examBookingUrl: "https://home.pearsonvue.com/ri/insurance",
    noCombinedExam: true,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  "south-carolina": {
    name: "South Carolina",
    abbreviation: "SC",
    slug: "south-carolina",
    doiName: "South Carolina Department of Insurance",
    doiUrl: "https://www.doi.sc.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/south-carolina/insurance",
    examBookingUrl: "https://home.pearsonvue.com/sc/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  "south-dakota": {
    name: "South Dakota",
    abbreviation: "SD",
    slug: "south-dakota",
    doiName: "South Dakota Division of Insurance",
    doiUrl: "https://dlr.sd.gov/insurance",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/south-dakota/insurance",
    examBookingUrl: "https://home.pearsonvue.com/sd/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  tennessee: {
    name: "Tennessee",
    abbreviation: "TN",
    slug: "tennessee",
    doiName: "Tennessee Department of Commerce and Insurance",
    doiUrl: "https://www.tn.gov/commerce/insurance",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/tennessee/insurance",
    examBookingUrl: "https://home.pearsonvue.com/tn/insurance",
    noCombinedExam: true,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  texas: {
    name: "Texas",
    abbreviation: "TX",
    slug: "texas",
    doiName: "Texas Department of Insurance",
    doiUrl: "https://www.tdi.texas.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/texas/insurance",
    examBookingUrl: "https://home.pearsonvue.com/tx/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  utah: {
    name: "Utah",
    abbreviation: "UT",
    slug: "utah",
    doiName: "Utah Insurance Department",
    doiUrl: "https://insurance.utah.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/utah/insurance",
    examBookingUrl: "https://home.pearsonvue.com/ut/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  vermont: {
    name: "Vermont",
    abbreviation: "VT",
    slug: "vermont",
    doiName: "Vermont Department of Financial Regulation – Insurance Division",
    doiUrl: "https://dfr.vermont.gov/insurance",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/vermont/insurance",
    examBookingUrl: "https://home.pearsonvue.com/vt/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  virginia: {
    name: "Virginia",
    abbreviation: "VA",
    slug: "virginia",
    doiName: "Virginia Bureau of Insurance",
    doiUrl: "https://www.scc.virginia.gov/pages/Bureau-of-Insurance",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/virginia/insurance",
    examBookingUrl: "https://home.pearsonvue.com/va/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 16, price: "$59", renewalYears: 2 },
      health: { hours: 16, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 16, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  washington: {
    name: "Washington",
    abbreviation: "WA",
    slug: "washington",
    doiName: "Washington Office of the Insurance Commissioner",
    doiUrl: "https://www.insurance.wa.gov",
    examProvider: "PSI",
    examProviderUrl: "https://test-takers.psiexams.com/waoic",
    examBookingUrl: "https://test-takers.psiexams.com/waoic",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  "west-virginia": {
    name: "West Virginia",
    abbreviation: "WV",
    slug: "west-virginia",
    doiName: "West Virginia Offices of the Insurance Commissioner",
    doiUrl: "https://www.wvinsurance.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/west-virginia/insurance",
    examBookingUrl: "https://home.pearsonvue.com/wv/insurance",
    noCombinedExam: true,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  wisconsin: {
    name: "Wisconsin",
    abbreviation: "WI",
    slug: "wisconsin",
    doiName: "Wisconsin Office of the Commissioner of Insurance",
    doiUrl: "https://oci.wi.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/wisconsin/insurance",
    examBookingUrl: "https://home.pearsonvue.com/wi/insurance",
    noCombinedExam: true,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
  wyoming: {
    name: "Wyoming",
    abbreviation: "WY",
    slug: "wyoming",
    doiName: "Wyoming Department of Insurance",
    doiUrl: "https://doi.wyo.gov",
    examProvider: "Pearson VUE",
    examProviderUrl: "https://home.pearsonvue.com/wyoming/insurance",
    examBookingUrl: "https://home.pearsonvue.com/wy/insurance",
    noCombinedExam: false,
    applicationBeforeExam: false,
    prelicensing: {
      life: { hours: 20, price: "$199" },
      health: { hours: 20, price: "$199" },
      lifeAndHealth: { hours: 40, price: "$199" },
    },
    ce: {
      life: { hours: 24, price: "$59", renewalYears: 2 },
      health: { hours: 24, price: "$59", renewalYears: 2 },
      lifeAndHealth: { hours: 24, price: "$59", renewalYears: 2 },
    },
    examInfo: { questions: 150, passingScore: 70, timeLimit: "2.5 hours" },
  },
};

export const ALL_STATE_SLUGS: string[] = Object.keys(STATES);

export function getStateBySlug(slug: string): StateData | undefined {
  return STATES[slug];
}
